package bpipe.cmd

import bpipe.PipelineCategory
import groovy.util.logging.Log

/**
 * Command that generates a GDSL (Groovy DSL Descriptor) file for IDE support.
 * <p>
 * This works by constructing the pipeline (evaluating all load() statements, 
 * segment definitions, etc.) without actually running it, then introspecting
 * the binding to discover all variables and pipeline stages that are in scope.
 * The result is a .gdsl file that IntelliJ IDEA can use for autocompletion
 * and type checking.
 */
@Log
class GenerateDSLCommand {

    List<String> args

    GenerateDSLCommand(List<String> args) {
        this.args = args
    }

    /**
     * Generate GDSL content from the current state of the pipeline after construction.
     * 
     * @param typedVariables    Map of variable names to their inferred type names
     * @param stages            Map of stage names to their type (always Closure)
     * @return                  The GDSL file content as a string
     */
    static String generateGDSLContent(Map<String, String> typedVariables, Map<String, String> stages) {

        StringBuilder sb = new StringBuilder()

        sb.append("// Generated by: bpipe generate-dsl\n")
        sb.append("// Date: ${new Date()}\n")
        sb.append("//\n")
        sb.append("// Place this file in your project root or source directory\n")
        sb.append("// for IntelliJ IDEA to recognize Bpipe pipeline variables and stages.\n")
        sb.append("\n")
        sb.append("def bpipeScriptContext = context(\n")
        sb.append("    filetypes: ['groovy'],\n")
        sb.append("    scope: scriptScope()\n")
        sb.append(")\n")
        sb.append("\n")
        sb.append("contributor(bpipeScriptContext) {\n")
        sb.append("\n")
        sb.append("    // Pipeline stages (available as both variables and callable methods)\n")

        stages.each { String name, String type ->
            sb.append("    property name: '${escapeGDSL(name)}', type: 'groovy.lang.Closure'\n")
        }

        sb.append("\n")
        sb.append("    // Variables defined in pipeline scripts and loaded libraries\n")

        typedVariables.each { String name, String type ->
            if(!stages.containsKey(name)) {
                sb.append("    property name: '${escapeGDSL(name)}', type: '${type}'\n")
            }
        }

        sb.append("\n")
        sb.append("    // Bpipe built-in methods available in pipeline stage bodies\n")
        sb.append("    method name: 'produce', type: 'void', params: [outputs: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'transform', type: 'void', params: [exts: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'filter', type: 'void', params: [exts: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'forward', type: 'void', params: [files: 'java.lang.Object']\n")
        sb.append("    method name: 'exec', type: 'void', params: [cmd: 'java.lang.String']\n")
        sb.append("    method name: 'exec', type: 'void', params: [cmd: 'java.lang.String', config: 'java.lang.String']\n")
        sb.append("    method name: 'succeed', type: 'void', params: [msg: 'java.lang.String']\n")
        sb.append("    method name: 'fail', type: 'void', params: [msg: 'java.lang.String']\n")
        sb.append("    method name: 'send', type: 'void', params: [details: 'java.util.Map']\n")
        sb.append("    method name: 'check', type: 'void', params: [name: 'java.lang.String', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'uses', type: 'void', params: [resources: 'java.util.Map', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'requires', type: 'void', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'var', type: 'void', params: [defaults: 'java.util.Map']\n")
        sb.append("    method name: 'load', type: 'void', params: [path: 'java.lang.String']\n")
        sb.append("    method name: 'segment', type: 'groovy.lang.Closure', params: [body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'msg', type: 'void', params: [message: 'java.lang.String']\n")
        sb.append("    method name: 'multi', type: 'void', params: [cmd: 'java.lang.String']\n")

        sb.append("\n")
        sb.append("    // Bpipe implicit variables available in pipeline stage bodies\n")
        sb.append("    property name: 'input', type: 'bpipe.PipelineInput'\n")
        sb.append("    property name: 'output', type: 'bpipe.PipelineOutput'\n")
        sb.append("    property name: 'branch', type: 'bpipe.Branch'\n")
        sb.append("    property name: 'threads', type: 'java.lang.Integer'\n")
        sb.append("    property name: 'memory', type: 'java.lang.Object'\n")
        sb.append("    property name: 'region', type: 'bpipe.RegionValue'\n")
        sb.append("}\n")
        sb.append("\n")
        sb.append("// Methods added to Closure by PipelineCategory (pipeline stage modifiers)\n")
        sb.append("contributor(context(ctype: 'groovy.lang.Closure')) {\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [args: 'java.lang.Object[]']\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [params: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'with', type: 'groovy.lang.Closure', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'with', type: 'groovy.lang.Closure', params: [args: 'java.lang.Object[]']\n")
        sb.append("    method name: 'when', type: 'groovy.lang.Closure', params: [condition: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'from', type: 'groovy.lang.Closure', params: [donors: 'groovy.lang.Closure[]']\n")
        sb.append("    method name: 'from', type: 'groovy.lang.Closure', params: [options: 'java.util.Map', pattern: 'java.lang.String[]']\n")
        sb.append("}\n")

        return sb.toString()
    }

    /**
     * Generate DSLD content for Eclipse IDE support.
     * 
     * @param typedVariables    Map of variable names to their inferred type names
     * @param stages            Map of stage names to their type (always Closure)
     * @return                  The DSLD file content as a string
     */
    static String generateDSLDContent(Map<String, String> typedVariables, Map<String, String> stages) {

        StringBuilder sb = new StringBuilder()

        sb.append("// Generated by: bpipe generate-dsl\n")
        sb.append("// Date: ${new Date()}\n")
        sb.append("//\n")
        sb.append("// Place this file in your project root or source directory\n")
        sb.append("// for Eclipse Groovy IDE to recognize Bpipe pipeline variables and stages.\n")
        sb.append("\n")
        sb.append("contribute(currentType(subType('groovy.lang.Script'))) {\n")
        sb.append("\n")
        sb.append("    // Pipeline stages (available as both variables and callable methods)\n")

        stages.each { String name, String type ->
            sb.append("    property name: '${escapeGDSL(name)}', type: 'groovy.lang.Closure'\n")
        }

        sb.append("\n")
        sb.append("    // Variables defined in pipeline scripts and loaded libraries\n")

        typedVariables.each { String name, String type ->
            if(!stages.containsKey(name)) {
                sb.append("    property name: '${escapeGDSL(name)}', type: '${type}'\n")
            }
        }

        sb.append("\n")
        sb.append("    // Bpipe built-in methods available in pipeline stage bodies\n")
        sb.append("    method name: 'produce', type: 'void', params: [outputs: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'transform', type: 'void', params: [exts: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'filter', type: 'void', params: [exts: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'forward', type: 'void', params: [files: 'java.lang.Object']\n")
        sb.append("    method name: 'exec', type: 'void', params: [cmd: 'java.lang.String']\n")
        sb.append("    method name: 'exec', type: 'void', params: [cmd: 'java.lang.String', config: 'java.lang.String']\n")
        sb.append("    method name: 'succeed', type: 'void', params: [msg: 'java.lang.String']\n")
        sb.append("    method name: 'fail', type: 'void', params: [msg: 'java.lang.String']\n")
        sb.append("    method name: 'send', type: 'void', params: [details: 'java.util.Map']\n")
        sb.append("    method name: 'check', type: 'void', params: [name: 'java.lang.String', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'uses', type: 'void', params: [resources: 'java.util.Map', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'requires', type: 'void', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'var', type: 'void', params: [defaults: 'java.util.Map']\n")
        sb.append("    method name: 'load', type: 'void', params: [path: 'java.lang.String']\n")
        sb.append("    method name: 'segment', type: 'groovy.lang.Closure', params: [body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'msg', type: 'void', params: [message: 'java.lang.String']\n")
        sb.append("    method name: 'multi', type: 'void', params: [cmd: 'java.lang.String']\n")

        sb.append("\n")
        sb.append("    // Bpipe implicit variables available in pipeline stage bodies\n")
        sb.append("    property name: 'input', type: 'bpipe.PipelineInput'\n")
        sb.append("    property name: 'output', type: 'bpipe.PipelineOutput'\n")
        sb.append("    property name: 'branch', type: 'bpipe.Branch'\n")
        sb.append("    property name: 'threads', type: 'java.lang.Integer'\n")
        sb.append("    property name: 'memory', type: 'java.lang.Object'\n")
        sb.append("    property name: 'region', type: 'bpipe.RegionValue'\n")
        sb.append("}\n")
        sb.append("\n")
        sb.append("// Methods added to Closure by PipelineCategory (pipeline stage modifiers)\n")
        sb.append("contribute(currentType('groovy.lang.Closure')) {\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [args: 'java.lang.Object[]']\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [params: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'with', type: 'groovy.lang.Closure', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'with', type: 'groovy.lang.Closure', params: [args: 'java.lang.Object[]']\n")
        sb.append("    method name: 'when', type: 'groovy.lang.Closure', params: [condition: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'from', type: 'groovy.lang.Closure', params: [donors: 'groovy.lang.Closure[]']\n")
        sb.append("    method name: 'from', type: 'groovy.lang.Closure', params: [options: 'java.util.Map', pattern: 'java.lang.String[]']\n")
        sb.append("}\n")

        return sb.toString()
    }

    /**
     * Infer the type name for a given value.
     */
    static String inferType(Object value) {
        if(value == null) return 'java.lang.Object'
        if(value instanceof Closure) return 'groovy.lang.Closure'
        if(value instanceof Map) return 'java.util.Map'
        if(value instanceof List) return 'java.util.List'
        if(value instanceof Integer) return 'java.lang.Integer'
        if(value instanceof Long) return 'java.lang.Long'
        if(value instanceof String) return 'java.lang.String'
        if(value instanceof Boolean) return 'java.lang.Boolean'
        if(value instanceof Double) return 'java.lang.Double'
        if(value instanceof Float) return 'java.lang.Float'
        if(value instanceof File) return 'java.io.File'
        return value.getClass().name
    }

    /**
     * Escape a string for use in a GDSL property name
     */
    private static String escapeGDSL(String value) {
        return value.replace("'", "\\'")
    }
}
