package bpipe.cmd

import bpipe.PipelineCategory
import groovy.util.logging.Log
import java.nio.file.Path
import java.util.regex.Pattern

/**
 * Command that generates a GDSL (Groovy DSL Descriptor) file for IDE support.
 * <p>
 * This works by constructing the pipeline (evaluating all load() statements, 
 * segment definitions, etc.) without actually running it, then introspecting
 * the binding to discover all variables and pipeline stages that are in scope.
 * The result is a .gdsl file that IntelliJ IDEA can use for autocompletion
 * and type checking.
 */
@Log
class GenerateDSLCommand {

    List<String> args

    GenerateDSLCommand(List<String> args) {
        this.args = args
    }

    /**
     * Generate GDSL content from the current state of the pipeline after construction.
     * 
     * @param typedVariables    Map of variable names to their inferred type names
     * @param stages            Map of stage names to their type (always Closure)
     * @return                  The GDSL file content as a string
     */
    static String generateGDSLContent(Map<String, String> typedVariables, Map<String, String> stages) {

        StringBuilder sb = new StringBuilder()

        sb.append("// Generated by: bpipe generate-dsl\n")
        sb.append("// Date: ${new Date()}\n")
        sb.append("//\n")
        sb.append("// Place this file in your project root or source directory\n")
        sb.append("// for IntelliJ IDEA to recognize Bpipe pipeline variables and stages.\n")
        sb.append("\n")
        sb.append("def bpipeScriptContext = context(\n")
        sb.append("    filetypes: ['groovy'],\n")
        sb.append("    scope: scriptScope()\n")
        sb.append(")\n")
        sb.append("\n")
        sb.append("contributor(bpipeScriptContext) {\n")
        sb.append("\n")
        sb.append("    // Pipeline stages (available as both variables and callable methods)\n")

        stages.each { String name, String type ->
            sb.append("    property name: '${escapeGDSL(name)}', type: 'groovy.lang.Closure'\n")
        }

        sb.append("\n")
        sb.append("    // Variables defined in pipeline scripts and loaded libraries\n")

        typedVariables.each { String name, String type ->
            if(!stages.containsKey(name)) {
                sb.append("    property name: '${escapeGDSL(name)}', type: '${type}'\n")
            }
        }

        sb.append("\n")
        sb.append("    // Bpipe built-in methods available in pipeline stage bodies\n")
        sb.append("    method name: 'produce', type: 'void', params: [outputs: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'transform', type: 'void', params: [exts: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'filter', type: 'void', params: [exts: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'forward', type: 'void', params: [files: 'java.lang.Object']\n")
        sb.append("    method name: 'exec', type: 'void', params: [cmd: 'java.lang.String']\n")
        sb.append("    method name: 'exec', type: 'void', params: [cmd: 'java.lang.String', config: 'java.lang.String']\n")
        sb.append("    method name: 'succeed', type: 'void', params: [msg: 'java.lang.String']\n")
        sb.append("    method name: 'fail', type: 'void', params: [msg: 'java.lang.String']\n")
        sb.append("    method name: 'send', type: 'void', params: [details: 'java.util.Map']\n")
        sb.append("    method name: 'check', type: 'void', params: [name: 'java.lang.String', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'uses', type: 'void', params: [resources: 'java.util.Map', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'requires', type: 'void', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'var', type: 'void', params: [defaults: 'java.util.Map']\n")
        sb.append("    method name: 'load', type: 'void', params: [path: 'java.lang.String']\n")
        sb.append("    method name: 'segment', type: 'groovy.lang.Closure', params: [body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'msg', type: 'void', params: [message: 'java.lang.String']\n")
        sb.append("    method name: 'multi', type: 'void', params: [cmd: 'java.lang.String']\n")

        sb.append("\n")
        sb.append("    // Bpipe implicit variables available in pipeline stage bodies\n")
        sb.append("    property name: 'input', type: 'bpipe.PipelineInput'\n")
        sb.append("    property name: 'output', type: 'bpipe.PipelineOutput'\n")
        sb.append("    property name: 'branch', type: 'bpipe.Branch'\n")
        sb.append("    property name: 'threads', type: 'java.lang.Integer'\n")
        sb.append("    property name: 'memory', type: 'java.lang.Object'\n")
        sb.append("    property name: 'region', type: 'bpipe.RegionValue'\n")
        sb.append("}\n")
        sb.append("\n")
        sb.append("// Methods added to Closure by PipelineCategory (pipeline stage modifiers)\n")
        sb.append("contributor(context(ctype: 'groovy.lang.Closure')) {\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [args: 'java.lang.Object[]']\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [params: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'with', type: 'groovy.lang.Closure', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'with', type: 'groovy.lang.Closure', params: [args: 'java.lang.Object[]']\n")
        sb.append("    method name: 'when', type: 'groovy.lang.Closure', params: [condition: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'from', type: 'groovy.lang.Closure', params: [donors: 'groovy.lang.Closure[]']\n")
        sb.append("    method name: 'from', type: 'groovy.lang.Closure', params: [options: 'java.util.Map', pattern: 'java.lang.String[]']\n")
        sb.append("}\n")

        return sb.toString()
    }

    /**
     * Generate DSLD content for Eclipse IDE support.
     * 
     * @param typedVariables    Map of variable names to their inferred type names
     * @param stages            Map of stage names to their type (always Closure)
     * @return                  The DSLD file content as a string
     */
    static String generateDSLDContent(Map<String, String> typedVariables, Map<String, String> stages) {

        StringBuilder sb = new StringBuilder()

        sb.append("// Generated by: bpipe generate-dsl\n")
        sb.append("// Date: ${new Date()}\n")
        sb.append("//\n")
        sb.append("// Place this file in your project root or source directory\n")
        sb.append("// for Eclipse Groovy IDE to recognize Bpipe pipeline variables and stages.\n")
        sb.append("\n")
        sb.append("contribute(currentType(subType('groovy.lang.Script'))) {\n")
        sb.append("\n")
        sb.append("    // Pipeline stages (available as both variables and callable methods)\n")

        stages.each { String name, String type ->
            sb.append("    property name: '${escapeGDSL(name)}', type: 'groovy.lang.Closure'\n")
        }

        sb.append("\n")
        sb.append("    // Variables defined in pipeline scripts and loaded libraries\n")

        typedVariables.each { String name, String type ->
            if(!stages.containsKey(name)) {
                sb.append("    property name: '${escapeGDSL(name)}', type: '${type}'\n")
            }
        }

        sb.append("\n")
        sb.append("    // Bpipe built-in methods available in pipeline stage bodies\n")
        sb.append("    method name: 'produce', type: 'void', params: [outputs: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'transform', type: 'void', params: [exts: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'filter', type: 'void', params: [exts: 'java.lang.Object', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'forward', type: 'void', params: [files: 'java.lang.Object']\n")
        sb.append("    method name: 'exec', type: 'void', params: [cmd: 'java.lang.String']\n")
        sb.append("    method name: 'exec', type: 'void', params: [cmd: 'java.lang.String', config: 'java.lang.String']\n")
        sb.append("    method name: 'succeed', type: 'void', params: [msg: 'java.lang.String']\n")
        sb.append("    method name: 'fail', type: 'void', params: [msg: 'java.lang.String']\n")
        sb.append("    method name: 'send', type: 'void', params: [details: 'java.util.Map']\n")
        sb.append("    method name: 'check', type: 'void', params: [name: 'java.lang.String', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'uses', type: 'void', params: [resources: 'java.util.Map', body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'requires', type: 'void', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'var', type: 'void', params: [defaults: 'java.util.Map']\n")
        sb.append("    method name: 'load', type: 'void', params: [path: 'java.lang.String']\n")
        sb.append("    method name: 'segment', type: 'groovy.lang.Closure', params: [body: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'msg', type: 'void', params: [message: 'java.lang.String']\n")
        sb.append("    method name: 'multi', type: 'void', params: [cmd: 'java.lang.String']\n")

        sb.append("\n")
        sb.append("    // Bpipe implicit variables available in pipeline stage bodies\n")
        sb.append("    property name: 'input', type: 'bpipe.PipelineInput'\n")
        sb.append("    property name: 'output', type: 'bpipe.PipelineOutput'\n")
        sb.append("    property name: 'branch', type: 'bpipe.Branch'\n")
        sb.append("    property name: 'threads', type: 'java.lang.Integer'\n")
        sb.append("    property name: 'memory', type: 'java.lang.Object'\n")
        sb.append("    property name: 'region', type: 'bpipe.RegionValue'\n")
        sb.append("}\n")
        sb.append("\n")
        sb.append("// Methods added to Closure by PipelineCategory (pipeline stage modifiers)\n")
        sb.append("contribute(currentType('groovy.lang.Closure')) {\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [args: 'java.lang.Object[]']\n")
        sb.append("    method name: 'using', type: 'groovy.lang.Closure', params: [params: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'with', type: 'groovy.lang.Closure', params: [params: 'java.util.Map']\n")
        sb.append("    method name: 'with', type: 'groovy.lang.Closure', params: [args: 'java.lang.Object[]']\n")
        sb.append("    method name: 'when', type: 'groovy.lang.Closure', params: [condition: 'groovy.lang.Closure']\n")
        sb.append("    method name: 'from', type: 'groovy.lang.Closure', params: [donors: 'groovy.lang.Closure[]']\n")
        sb.append("    method name: 'from', type: 'groovy.lang.Closure', params: [options: 'java.util.Map', pattern: 'java.lang.String[]']\n")
        sb.append("}\n")

        return sb.toString()
    }

    /**
     * Generate content for ctags-based editor support.
     * <p>
     * Editors such as vim and emacs do not understand GDSL/DSLD descriptors.
     * Instead they rely on a tags file in the Exuberant Ctags format to navigate
     * source code. This method produces two companion files:
     * <ul>
     *   <li>A stub Groovy file whose lines act as fallback anchors, and</li>
     *   <li>A tags file in Exuberant Ctags extended format whose entries point at
     *       the real definition where possible, and at the stub otherwise.</li>
     * </ul>
     * <p>
     * Pipeline stages and variables written by the pipeline author are resolved
     * to the actual line in the script (or a loaded library) that defines them,
     * so tag navigation opens the real source. Only symbols with no user-facing
     * definition in the pipeline source - Bpipe's built-in methods, implicit
     * variables and stage modifiers - are anchored in the stub file, along with
     * any user symbol that could not be located.
     *
     * @param typedVariables    Map of variable names to their inferred type names
     * @param stages            Map of stage names to their type (always Closure)
     * @param stubFileName      The name/path of the stub file that fallback tag
     *                          entries should reference
     * @param definitionFiles   Script and library files to scan for the real
     *                          definition lines of user stages and variables
     *                          (optional)
     * @param pathBase          Directory the tags file lives in, used to compute
     *                          relative paths for real source files (optional)
     * @return                  A map with keys 'stub' (stub source content) and
     *                          'tags' (Ctags tags file content)
     */
    static Map<String, String> generateCtagsContent(Map<String, String> typedVariables, Map<String, String> stages, String stubFileName, List<File> definitionFiles = [], File pathBase = null) {

        List<String> lines = []
        List<Map<String, Object>> tags = []

        // Record a tag entry that points at a real definition line
        def addRealTag = { String name, File file, int line, String kind ->
            tags.add([name: name, file: pathForTags(file, pathBase), line: line, kind: kind])
        }

        // Add an anchor line to the stub file and record a tag entry pointing at it
        def addStubAnchor = { String name, String kind, String comment ->
            int anchorLine = lines.size() + 1
            if(kind == 'f') {
                lines.add("${name} = {")
                lines.add("    // ${comment}")
                lines.add("}")
            }
            else {
                lines.add("def ${name} = null // ${comment}")
            }
            tags.add([name: name, file: stubFileName, line: anchorLine, kind: kind])
        }

        // Try to resolve a symbol to its real definition line in the given files,
        // otherwise anchor it in the stub file
        def addSymbol = { String name, boolean isStage, String kind, String comment ->
            Map<String,Object> definition = findDefinition(definitionFiles, name, isStage)
            if(definition) {
                addRealTag(name, (File)definition.file, (Integer)definition.line, kind)
            }
            else {
                addStubAnchor(name, kind, comment)
            }
        }

        // Header comments for the stub file
        lines.add("// Generated by: bpipe generate-dsl")
        lines.add("// Date: ${new Date()}")
        lines.add("//")
        lines.add("// Stub definitions for ctags-based (Exuberant Ctags) editor support.")
        lines.add("// This file is NOT executed by Bpipe. It only provides anchor lines for")
        lines.add("// Bpipe built-in methods and any symbols whose definition could not be")
        lines.add("// located in your pipeline scripts. Pipeline stages and variables you")
        lines.add("// define are resolved directly in bpipe.tags to your real source files.")
        lines.add("")

        // Pipeline stages
        lines.add("// Pipeline stages (available as both variables and callable methods)")
        lines.add("")
        for(String name in stages.keySet().sort()) {
            addSymbol(name, true, 'f', 'Bpipe pipeline stage - see your pipeline script for the actual definition')
        }

        // Variables defined in pipeline scripts and loaded libraries
        lines.add("")
        lines.add("// Variables defined in pipeline scripts and loaded libraries")
        lines.add("")
        for(String name in typedVariables.keySet().sort()) {
            if(!stages.containsKey(name)) {
                addSymbol(name, false, 'v', 'type: ' + typedVariables[name])
            }
        }

        // Bpipe built-in methods available in pipeline stage bodies
        def builtInMethods = [
            'produce', 'transform', 'filter', 'forward', 'exec', 'succeed', 'fail',
            'send', 'check', 'uses', 'requires', 'var', 'load', 'segment', 'msg', 'multi'
        ]
        lines.add("")
        lines.add("// Bpipe built-in methods available in pipeline stage bodies")
        lines.add("")
        for(String name in builtInMethods) {
            addStubAnchor(name, 'f', 'Bpipe built-in method - see the Bpipe documentation')
        }

        // Bpipe implicit variables available in pipeline stage bodies
        def implicitVariables = [
            'input':'bpipe.PipelineInput', 'output':'bpipe.PipelineOutput', 'branch':'bpipe.Branch',
            'threads':'java.lang.Integer', 'memory':'java.lang.Object', 'region':'bpipe.RegionValue'
        ]
        lines.add("")
        lines.add("// Bpipe implicit variables available in pipeline stage bodies")
        lines.add("")
        for(entry in implicitVariables.entrySet()) {
            addStubAnchor(entry.key, 'v', 'type: ' + entry.value)
        }

        // Methods added to Closure by PipelineCategory (pipeline stage modifiers)
        def modifierMethods = ['using', 'with', 'when', 'from']
        lines.add("")
        lines.add("// Pipeline stage modifier methods (added to stages by PipelineCategory)")
        lines.add("")
        for(String name in modifierMethods) {
            addStubAnchor(name, 'f', 'Bpipe pipeline stage modifier - see the Bpipe documentation')
        }

        String stubContent = lines.join("\n") + "\n"

        // Build the tags file in Exuberant Ctags extended format.
        StringBuilder tagsSb = new StringBuilder()
        tagsSb.append("!_TAG_FILE_FORMAT\t2\t/extended format; --format=1 will not append ;\" to lines/\n")
        tagsSb.append("!_TAG_FILE_SORTED\t1\t/0=unsorted, 1=sorted, 2=foldcase/\n")
        tagsSb.append("!_TAG_PROGRAM_NAME\tBpipe\t//\n")
        String bpipeVersion = System.getProperty("bpipe.version")
        if(bpipeVersion) {
            tagsSb.append("!_TAG_PROGRAM_VERSION\t${bpipeVersion}\t//\n")
        }
        tagsSb.append("!_TAG_PROGRAM_URL\thttp://www.southernstorm.com.au/bpipe.html\t//\n")

        // Emit the tag entries, sorted by the full tag line so the file is in
        // byte order and stays valid even if two symbols share a name
        // (e.g. a stage literally named 'produce').
        List<String> tagLines = tags.collect { Map<String,Object> t ->
            "${t.name}\t${t.file}\t${t.line};\"\tkind:${t.kind}"
        }
        tagLines.sort()
        tagLines.each { String line -> tagsSb.append(line + "\n") }

        return [stub: stubContent, tags: tagsSb.toString()]
    }

    /**
     * Locate the definition line of a symbol in the given source files.
     *
     * @param files     Script and library files to search (in priority order)
     * @param name      The symbol name to locate
     * @param isStage   When true, look for a closure assignment ({@code name = \{});
     *                  otherwise look for a plain assignment ({@code name = ...})
     * @return          A map with 'file' (the containing File) and 'line' (1-based
     *                  line number), or null if not found in any file
     */
    static Map<String,Object> findDefinition(List<File> files, String name, boolean isStage) {
        for(File f in (files ?: [])) {
            if(f == null || !f.exists())
                continue
            int line = findDefinitionLine(f, name, isStage)
            if(line > 0)
                return [file: f, line: line]
        }
        return null
    }

    /**
     * Find the 1-based line number of a symbol definition within a single file,
     * or 0 if the symbol is not defined there.
     */
    static int findDefinitionLine(File file, String name, boolean isStage) {
        String quoted = Pattern.quote(name)
        String pattern = isStage
            ? "^\\s*(?:def\\s+)?${quoted}\\s*=\\s*\\{"
            : "^\\s*(?:def\\s+)?${quoted}\\s*="
        Pattern p = Pattern.compile(pattern)
        int result = 0
        file.eachLine { String line, int number ->
            if(result != 0)
                return
            String trimmed = line.trim()
            if(!trimmed || trimmed.startsWith('//') || trimmed.startsWith('*') || trimmed.startsWith('/*'))
                return
            if(p.matcher(line).find())
                result = number
        }
        return result
    }

    /**
     * Work out the file path to embed in a tags entry. If the source lives under
     * the tags file's directory, a path relative to it is used (so the tags file
     * can be moved with its project); otherwise an absolute path is used.
     */
    private static String pathForTags(File file, File pathBase) {
        try {
            if(file != null && pathBase != null) {
                Path base = pathBase.toPath().toAbsolutePath().normalize()
                Path target = file.toPath().toAbsolutePath().normalize()
                if(target.startsWith(base))
                    return base.relativize(target).toString()
            }
        }
        catch(Exception e) {
            // fall through to simple handling below
        }
        return file != null ? file.path : ''
    }

    /**
     * Infer the type name for a given value.
     */
    static String inferType(Object value) {
        if(value == null) return 'java.lang.Object'
        if(value instanceof Closure) return 'groovy.lang.Closure'
        if(value instanceof Map) return 'java.util.Map'
        if(value instanceof List) return 'java.util.List'
        if(value instanceof Integer) return 'java.lang.Integer'
        if(value instanceof Long) return 'java.lang.Long'
        if(value instanceof String) return 'java.lang.String'
        if(value instanceof Boolean) return 'java.lang.Boolean'
        if(value instanceof Double) return 'java.lang.Double'
        if(value instanceof Float) return 'java.lang.Float'
        if(value instanceof File) return 'java.io.File'
        return value.getClass().name
    }

    /**
     * Escape a string for use in a GDSL property name
     */
    private static String escapeGDSL(String value) {
        return value.replace("'", "\\'")
    }
}
